# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gladys Project
description: > # this means to ignore newlines until "baseurl:"
    Gladys is an open-source home assistant which runs on your Raspberry Pi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gladysproject.com" # the base hostname & protocol for your site, e.g. http://example.com

## I18N
languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  fr: Français
  en: English

# Social network
twitter_username: gladysproject
github_username:  gladysproject
facebook_username: gladysproject
instagram_username: gladysproject
plugins: [jekyll-feed, jekyll-paginate-v2]

# Build settings
markdown: kramdown
theme: minima

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num"
  sort_field: 'date'
  sort_reverse: true

comments:
  disqus:
    short_name: 
    api_key: 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
