

[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/fr_feed.xml"
  to = "/feed.xml"
  status = 301
  force = true


[[redirects]]
  from = "http://dazzling-jennings-ad108b.netlify.com/*"
  to = "http://gladysproject.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dazzling-jennings-ad108b.netlify.com/*"
  to = "https://gladysproject.com/:splat"
  status = 301
  force = true